name:                SystemFOmegaMuSemi
version:             0.1.0.0
github:              "githubuser/SystemFOmegaMuSemi"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2023 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/SystemFOmegaMuSemi#readme>

dependencies:
- base >= 4.7 && < 5
- containers >=0.5.9
- ghc
- mtl >= 2.2.1
- time >= 1.12.2
- array >= 0.5.4.0

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  SystemFOmegaMuSemi-exe:
    main:                Main.hs
    source-dirs:         app
    build-tools:
    - alex
    - happy
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - SystemFOmegaMuSemi

tests:
  SystemFOmegaMuSemi-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - SystemFOmegaMuSemi

  SystemFOmegaMuSemi-test-QuickCheck:
      main: QuickCheckSpec.hs
      source-dirs:
        - test/QuickCheck
      dependencies:
        - SystemFOmegaMuSemi
        - QuickCheck
        - hspec

  SystemFOmegaMuSemi-test-units:
      main: UnitSpec.hs
      source-dirs: test
      dependencies:
        - SystemFOmegaMuSemi
        - QuickCheck
        - hspec >= 2.7.1
        - hspec-expectations >= 0.8.2
        - hspec-discover >= 2.7.1
        - split >= 0.2.3.3
        - HUnit >= 1.6.0.0

